### ISSUE TITLE
testIn(backgroundScope) example not throwing exception for unconsumed event

### ISSUE THREAD

**Issue by jonathanpun** [cashapp/turbine#234]
I am trying to run the example in the README.md, but i found the outcome of the test does not match what's stated in the example.

below is the code copied from the "Consuming All Events" section in README.md.

[Example Project](https://github.com/jonathanpun/TurbineExample)
``` 
import app.cash.turbine.testIn
import junit.framework.TestCase.assertEquals
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.Test

class TurbineTest {
    @Test
    fun turbineTest() =
        runTest {
            val turbine = flowOf("one", "two").testIn(backgroundScope)
            assertEquals("one", turbine.awaitItem())
        }
}
 ```
 
Expected outcome: the test would fail with unconsumed event exception as stated in the example
Actual outcome: the test passes

turbine version: 0.13.0
kotlinx-coroutines-test version: 1.7.1

**Comment by jingibus** [comment]
Thanks for the catch. This was likely broken while addressing issue #165.

**Comment by JakeWharton** [comment]
Fixed, although you have to use the `turbine { }` wrapper now.

**Comment by adamsousa** [comment]
I'm still experiencing this in 1.0.0, even when using `turbineScope`

```
@Test
fun turbineTest() = runTest {
    turbineScope {
        val turbine = flowOf("one", "two").testIn(backgroundScope)
        assertEquals("one", turbine.awaitItem())
    }
}
```

Also noticed a small documentation error. Under "Consuming All Events" section, it shows `assertEquals()` being invoked from the `ReceiveTurbine` object, instead of `awaitEvent()`:

```
runTest {
  turbineScope {
    val turbine = flowOf("one", "two").testIn(backgroundScope)
    turbine.assertEquals("one", awaitItem())
  }
}
```
